# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rony Rodriguez
tagline:          'Development Policy Student'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://rrmaximiliano.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
