# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rony Rodriguez
tagline:          Development Policy Student
description:      "Development Policy Student"
url:              http://rrmaximiliano.github.io
baseurl:          /

author:
  name:           'Karlo Espiritu'
  url:            https://twitter.com/karloespiritu

paginate:         5

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/karloespiritu/blackdoc
