# Dependencies
markdown:         kramdown
pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rony Rodriguez
tagline:          'Development Policy Student'
description:      'Development Policy Student at <a href="https://kdischool.ac.kr" target="_blank">KDI School, South Korea</a>.'
url:              https://rrmaximiliano.github.io

author:
  name:           Rony Rodriguez
  githurl:        rrmaximiliano.github.io
  email:          maximiliano@kdis.ac.kr

paginate:         5

github:
  repo:           https://github.com/rrmaximiliano
