# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Rony Rodriguez
tagline:          'Development Policy Student'
description:      'Development Policy Student at <a href="https://kdischool.ac.kr"KDI School</a>.'
url:              https://rrmaximiliano.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
