# Dependencies
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rony Rodriguez
tagline:          'Development Policy Student'
description:      'Graduate Student<br>Development Policy<br><a href="https://kdischool.ac.kr" target="_blank">KDI School<br>South Korea'
url:              http://rrmaximiliano.github.io

author:
  name:           Rony Rodriguez
  url:            rrmaximiliano.github.io
  giturl:         rrmaximiliano.github.io
  email:          maximiliano@kdis.ac.kr
  google_scholar: https://scholar.google.com/citations?user=PA_LMYMAAAAJ&hl=en

paginate:          5
paginate_path:    '/resources/page:num/'

version:          June 2017

github:
  repo:           https://github.com/rrmaximiliano
