project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true
    
  output-dir: docs
  render:
    - "*.qmd"

resources:
  - fonts/
  - go/

website:
  search: false
  google-analytics: "UA-134175775-1"
  page-navigation: true
  site-url: "https://www.rrmaximiliano.github.io/"
  repo-url: "https://github.com/RRMaximiliano/rrmaximiliano.github.io"
  navbar:
    background: "#FFFF"
    pinned: true

    left:
      - text: "Rony Rodríguez-Ramírez"
        file: index.qmd

    right:
      - text: "Research"
        file: research/index.qmd
      - text: "Teaching"
        file: teaching/index.qmd
      - text: "Software and Data"
        file: projects/index.qmd
      - text: "CV"
        file: cv/index.qmd
      - text: "Blog"
        file: blog/index.qmd
      - text: "Resources"
        file: resource/index.qmd

  page-footer:
    border: true  
    left: >-
      &#169; <span id="copy-year"></span> Rony Rodríguez-Ramírez
      <script>
        document.addEventListener('DOMContentLoaded', () =>
          document.getElementById('copy-year').textContent = new Date().getFullYear()
        );
      </script>
    right: >-
      [Contact Me](/contact.qmd) | [View the source on {{< fa brands github >}} GitHub]({{< var github-url >}})

format:
  html:
    theme:
      light: 
      - html/custom.scss
    toc: true
