baseURL: https://rrmaximiliano.github.io
languageCode: en
DefaultContentLanguage: en
title: Website of RRMaximiliano
theme: anatole
summarylength: 5
enableEmoji: yes
enableRobotsTXT: yes
pygmentsUseClasses: yes
pygmentsCodeFences: yes
pygmentsCodefencesGuessSyntax: yes
googleAnalytics: UA-134175775-1
params:
  author: Rony Rodriguez-Ramirez
  customCss: []
  customJs: []
  description: Aspiring Development Economist
  doNotLoadAnimations: yes
  favicon: favicons/favicon.ico
  images: images/site-feature-image.png
  keywords: ''
  mainSections:
  math:
    enable: no
    use: katex
  profilePicture: images/rony.jpg
  simpleAnalytics: {}
  socialIcons:
    - icon: fab fa-github
      title: GitHub
      url: https://github.com/rrmaximiliano
    - icon: fab fa-twitter
      title: twitter
      url: https://www.twitter.com/rrmaximiliano
    - icone: fab fa-twitch
      title: twitch
      url: https://www.twitch.com/rrmaximiliano
    - icon: fas fa-envelope
      title: e-mail
      url: mailto:rodriguezramirez@worldbank.org
  title: Rony Rodrigo Maximiliano Rodriguez-Ramirez
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 100
    - identifier: bio
      name: Bio
      weight: 200
      url: /bio/      
    - identifier: research
      name: Research
      url: /research/
      weight: 300
    - identifier: teaching
      name: Teaching
      url: /teaching/
      weight: 400
    - identifier: data
      name: Data
      urle: /data/
      weight: 500
    - identifier: cv
      name: CV
      url: /static/docs/rony-rodriguez-cv.pdf
      weight: 600      
    - identifier: posts
      name: Posts
      url: /post/
      weight: 700
